site:
  title: Applied Azure AI
  url: https://frazier-at-cpcc.github.io/csc214-oer
  start_page: applied-azure-ai::index.adoc
  keys:
    copyright_year: '2026'

content:
  sources:
    - url: .
      branches: HEAD

ui:
  bundle:
    url: ./ui/build/ui-bundle.zip

output:
  dir: ./build/site
